# Telegram bot properties
telegrambot_token: "5200885780:AAHKYBPD6Y5PCYwfExQXHjocGGeBb7DD1RM"
telegrambot_username: "lifelogging_bot"
telegrambot_webhook: "https://d15c-176-193-236-18.ngrok.io"

# Spring properties
spring:
  application:
    name: telegram-service
  rabbitmq:
    host: localhost # RabbitMQ host.
    username: guest # Login user to authenticate to the broker.
    password: guest # Login to authenticate against the broker.
    port: 5673 # RabbitMQ port.

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8083   # HTTP (Tomcat) port
#  servlet:
#    context-path:

constants:
  rabbit:
    queue: "data-queue"
    binding:
    routing-key: "data.#"
    exchange: "data-exchange"


logging:
  level:
    web: TRACE